version: 2
jobs:
  update:
    docker:
      - image: golang:1.12-alpine3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "43:e2:77:cf:61:69:69:bf:ed:21:93:86:60:8a:a5:50"
      - run: apk add --update git openssh
      - run: git checkout master
      - run: git config --global user.email rade1500@gmail.com
      - run: git config user.name "morix1500"
      - run: go run main.go
      - run: git add .
      - run: git commit -m "auto generate" || exit 0
      - run: git push origin master

workflows:
  version: 2
  workflow:
    jobs:
      - update
#  workflow:
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - update
