version: 2
jobs:
  update:
    docker:
      - image: golang:1.12-alpine3.9
    steps:
      - checkout
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: apk add --update git openssh
      - run: git checkout master
      - run: git config --global user.email rade1500@gmail.com
      - run: git config user.name "morix1500"
      - run: go run main.go
      - run:
          command: |
            git add .
            git commit -m "auto generate" || exit 0
            git push origin master

workflows:
  version: 2
  workflow:
    jobs:
      - update
#  workflow:
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - update
